version: '3.8'

services:
  # Frontend Angular application
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: chakra-frontend-demo
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chakra-network
    restart: unless-stopped

  # Backend FastAPI service in demo mode
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: chakra-backend-demo
    environment:
      - DATABASE_URL=sqlite:///data/chakra.db
      - SECRET_KEY=c3907fe25d74b6b7923e24d5090e2d5b73f71d5d3a51ff6197d4077f800f32a3
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - DEMO_MODE=true
      - CHAKRA_LIGHTWEIGHT_MODE=true
      - PYTHONUNBUFFERED=1
    volumes:
      - chakra-demo-data:/app/data
    ports:
      - "8000:8000"
    networks:
      - chakra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  chakra-network:
    driver: bridge

# Named volumes for data persistence
# Using named volumes instead of bind mounts for better Windows compatibility
volumes:
  chakra-demo-data:
    driver: local